### ISSUE TITLE
H2H and sudden disconnects - how to deal with NoPeerConnectionException?

### ISSUE THREAD

**Issue by albrechta** [Hive2Hive/Hive2Hive#123]
I have a question regarding the correct or intended usage of the H2H API.

What do I do if I get disconnected from the network due to a network failure or whatever reason?  I probably get a ```NoPeerConnectionException``` after a while.  Then there are several options.

Should I: 
- call connect(someNewNetworkConfiguration) again on the existing node instance? 
    - What about the session: Do I need to login again?
    - new event bus is created in this case, which breaks all existing wiring between the bus and objects (may consider this a bug... Probably should be related to the lifetime of the other managers?)
- no reuse of all "old" instances, i.e. create a new node instance and do the regular setup? (create/connect/login etc.)?

Thanks for any input!

**Comment by nicoruti** [comment]
> What about the session: Do I need to login again?

The session should remain ok, when reconnecting, it should work without logging in again. To be sure that the old connection is wiped completely, I added a method <code>IH2HNode#disconnectKeepSession()</code>.
<br/>

> new event bus is created in this case, which breaks all existing wiring between the bus and objects (may consider this a bug... Probably should be related to the lifetime of the other managers?)

The event bus indeed is a problem. There are two solutions:
- Attach it to a connection (thus it will be destroyed when calling 'disconnect')
- Attach it to the node. In this case, we would need to introduce a 'shutdown' method such that the event bus can shut down gracefully. Otherwise it will run forever.

To keep the API simple, we're currently having the event bus connection-specific, thus it will shutdown at disconnection.
<br/>

I would try to re-connect with the same node instance, since this is also easier for you not to create a new instance every time this exception is thrown. Just consider re-attaching your listener to the event bus.

```
try {
 ...
} catch(NoPeerConnectionException e) {
 node.disconnectKeepSession(); // disconnect properly while keeping the session
 node.connect();
 node.getEventBus().subscribe(...)
}
